import { getValidRows } from "../shared/helpers";

const cleanObjectName = (name) => (name || '').trim().replace(/\s+/g, '_');

export const getStoredProcSQL = (
    rows,
    objectRowData,
    detailsDataMap = {},
    detailsDefs,
    enableAudit = false,
    detailsTableTypes = {} // Track toggle state: true = Separate Table, false = Part of Main Table
) => {

    const validRows = getValidRows(rows);

    const dbName = objectRowData.find(row => row.object === 'DB')?.name;
    const spRow = objectRowData.find(row => row.object === 'StoredProcedure');
    const objectName = cleanObjectName(spRow?.name || '');

    if (!dbName || !objectName) {
        alert('Please provide DB Name, SP Name and at least one column.');
        return {};
    }

    const tableName = `tbl_${objectName}`;
    const procName = `sp_${objectName}`;

    const isStringType = (type) => {
        const strTypes = ['VARCHAR', 'NVARCHAR', 'TEXT', 'CHAR', 'NCHAR'];
        return strTypes.includes(type?.toUpperCase());
    };

    const isDateType = (type) => {
        const dateTypes = ['DATE', 'DATETIME', 'DATETIME2', 'SMALLDATETIME'];
        return dateTypes.includes(type?.toUpperCase());
    };

    const isNumberType = (type) => {
        const numTypes = [
            "INT", "BIGINT", "SMALLINT", "TINYINT", "DECIMAL",
            "NUMERIC", "FLOAT", "REAL", "MONEY", "SMALLMONEY"
        ];
        return numTypes.includes(type?.toUpperCase());
    };

    const format3ColsPerRow = (arr, indentSpaces = 12, isIdentifier = true) => {
        const indent = ' '.repeat(indentSpaces);
        const rowsArr = [];
        for (let i = 0; i < arr.length; i += 3) {
            const chunk = arr.slice(i, i + 3).map(col => isIdentifier ? `[${col}]` : col);
            rowsArr.push(indent + chunk.join(', '));
        }
        return rowsArr.join(',\n');
    };

    const buildStoredProc = (contentRows, tblName, spName) => {

        const hasConstraint = (constraints, types = []) => {
            if (!constraints) return false;
            const normalized = constraints
                .toString()
                .toUpperCase()
                .replace(/\s+/g, ' ')
                .trim();

            return types.some(type =>
                normalized.includes(type.toUpperCase())
            );
        };

        const pkCols = contentRows.filter(col =>
            hasConstraint(col.constraints, ["PK", "PRIMARY KEY"])
        );
        const aiCols = contentRows.filter(col =>
            hasConstraint(col.constraints, ["AI", "IDENTITY"])
        );
        const fkCols = contentRows.filter(col =>
            hasConstraint(col.constraints, ["FK", "FOREIGN KEY"])
        );
        const nnCols = contentRows.filter(col =>
            hasConstraint(col.constraints, ["NN", "NOT NULL"])
        );

        const hasPK = pkCols.length > 0 || aiCols.length > 0;
        const hasFK = fkCols.length > 0;
        const hasNN = nnCols.length > 0;

        const isAutoGeneratedID = !hasPK && !hasFK && !hasNN;

        const varbinaryCols = contentRows.filter(
            col => col.dataType?.toUpperCase() === "VARBINARY"
        );

        let paramRows = contentRows.filter(col => col.dataType?.toUpperCase() !== "GRID");

        let inputParamsList = [];
        if (isAutoGeneratedID) {
            inputParamsList.push(`    @id INT = 0`);
        }

        paramRows.forEach(col => {
            const safeFieldName = cleanObjectName(col.fieldName);
            const uddType = col.existingUDD && col.existingUDD.trim() !== ''
                ? col.existingUDD.trim()
                : `udd_${safeFieldName}`;
            inputParamsList.push(`    @${safeFieldName} ${uddType}`);
        });

        let inputParams = inputParamsList.join(',\n');

        const insertableRows = paramRows.filter(col => {
            if (hasConstraint(col.constraints, ["AI", "IDENTITY"])) return false;
            const field = col.fieldName.toLowerCase();
            return field !== 'modified_by' && field !== 'modified_date';
        });

        const insertFieldsList = insertableRows.map(col => cleanObjectName(col.fieldName));
        const insertFieldsFormatted = format3ColsPerRow(insertFieldsList, 12, true);

        const insertValuesList = insertableRows.map(col => {
            const safeField = cleanObjectName(col.fieldName);
            const field = safeField.toLowerCase();

            if (field === 'created_date') return 'SYSDATETIME()';
            if (field === 'created_by') return '@created_by';
            if (field === 'company_code') return '@company_code';
            if (field === 'location_code') return '@location_code';

            if (col.dataType?.toUpperCase() === "VARBINARY") {
                return `@${safeField}_data`;
            }

            return isStringType(col.dataType)
                ? `TRIM(@${safeField})`
                : `@${safeField}`;
        });
        const insertValuesFormatted = format3ColsPerRow(insertValuesList, 12, false);

        let whereCols = [];
        if (hasPK) {
            whereCols = pkCols.length > 0 ? pkCols : aiCols;
        } else if (hasFK || hasNN) {
            const combinedMap = new Map();
            [...fkCols, ...nnCols].forEach(col => combinedMap.set(col.fieldName, col));
            whereCols = Array.from(combinedMap.values());
        }

        const updateAssignments = paramRows
            .filter(col => {
                const field = col.fieldName.toLowerCase();
                const isWhereCol = whereCols.some(w => w.fieldName === col.fieldName);
                return !isWhereCol && field !== 'created_date' && field !== 'created_by';
            })
            .map(col => {
                const safeField = cleanObjectName(col.fieldName);
                const field = safeField.toLowerCase();

                if (field === 'modified_date')
                    return `            [${safeField}] = SYSDATETIME()`;

                if (field === 'modified_by')
                    return `            [${safeField}] = @modified_by`;

                if (field === 'company_code')
                    return `            [${safeField}] = @company_code`;

                if (field === 'location_code')
                    return `            [${safeField}] = @location_code`;

                if (col.dataType?.toUpperCase() === "VARBINARY") {
                    return `            [${safeField}] = @${safeField}_data`;
                }

                return isStringType(col.dataType)
                    ? `            [${safeField}] = TRIM(@${safeField})`
                    : `            [${safeField}] = @${safeField}`;
            })
            .join(',\n');

        let selectFieldsList = contentRows.filter(col => col.dataType?.toUpperCase() !== "GRID").map(col => cleanObjectName(col.fieldName));
        if (isAutoGeneratedID) {
            selectFieldsList.unshift('id');
        }
        const selectFieldsFormatted = format3ColsPerRow(selectFieldsList, 12, true);

        let script = `USE [${dbName}];\nGO\n\nCREATE PROCEDURE [dbo].[${spName}]\n(\n    @mode udd_mode,\n${inputParams}\n)\nAS\nBEGIN\n`;

        const auditWhereClause = enableAudit 
            ? `\n        AND [company_code] = @company_code\n        AND [location_code] = @location_code`
            : '';

        let whereConditionScript = '';
        if (isAutoGeneratedID) {
            whereConditionScript = `[id] = @id`;
        } else if (whereCols.length > 0) {
            whereConditionScript = whereCols.map(col => {
                const safeName = cleanObjectName(col.fieldName);
                return `[${safeName}] = ${isStringType(col.dataType) ? `TRIM(@${safeName})` : `@${safeName}`}`;
            }).join('\n        AND ');
        }

        const nullHandling = paramRows
            .map(col => {
                const field = cleanObjectName(col.fieldName);
                const datatype = col.dataType?.toUpperCase();

                if (isNumberType(datatype)) {
                    return `    SELECT @${field} = ISNULL(@${field}, 0)`;
                }

                return `    SELECT @${field} = ISNULL(RTRIM(LTRIM(@${field})), '')`;
            })
            .join('\n');

        const dateNullHandling = paramRows
            .filter(col => isDateType(col.dataType))
            .map(col => {
                const field = cleanObjectName(col.fieldName);
                return `    IF @${field} = ''\n        SET @${field} = NULL;`;
            })
            .join('\n');

        if (isAutoGeneratedID) {
            script += `    SELECT @id = ISNULL(@id, 0)\n`;
        }

        script += `${nullHandling}\n\n`;
        if (dateNullHandling) {
            script += `${dateNullHandling}\n\n`;
        }

        const notNullValidation = paramRows
            .filter(col =>
                hasConstraint(col.constraints, [
                    "NN",
                    "NOT NULL",
                    "PK",
                    "PRIMARY KEY"
                ])
            )
            .map(col => {
                const field = cleanObjectName(col.fieldName);
                const datatype = col.dataType?.toUpperCase();

                if (isNumberType(datatype)) {
                    return `        IF ISNULL(@${field}, 0) = 0 OR @${field} IS NULL\n        BEGIN\n            RAISERROR('${field} should not be blank', 16, 3)\n            RETURN\n        END`;
                }

                if (isDateType(datatype)) {
                    return `        IF @${field} IS NULL\n        BEGIN\n            RAISERROR('${field} should not be blank', 16, 3)\n            RETURN\n        END`;
                }

                return `        IF ISNULL(TRIM(@${field}), '') = '' OR @${field} IS NULL\n        BEGIN\n            RAISERROR('${field} should not be blank', 16, 3)\n            RETURN\n        END`;
            })
            .join('\n\n');

        if (varbinaryCols.length > 0) {
            script += '    -- VARBINARY conversion\n';
            varbinaryCols.forEach(col => {
                const field = cleanObjectName(col.fieldName);
                script += `    DECLARE @${field}_data VARBINARY(MAX)\n`;
                script += `    SET @${field}_data = CAST(@${field} AS VARBINARY(MAX))\n\n`;
            });
        }

        script += `    IF @mode = 'I'\n    BEGIN\n`;
        if (notNullValidation) {
            script += `${notNullValidation}\n\n`;
        }

        script += `        INSERT INTO [${tblName}] (\n${insertFieldsFormatted}\n        )\n        VALUES (\n${insertValuesFormatted}\n        )\n    END`;

        if (whereConditionScript) {
            script += `\n\n    ELSE IF @mode = 'U'\n    BEGIN\n        UPDATE [${tblName}]\n        SET\n${updateAssignments}\n        WHERE \n            ${whereConditionScript}${auditWhereClause};\n    END`;

            script += `\n\n    ELSE IF @mode = 'D'\n    BEGIN\n        DELETE FROM [${tblName}]\n        WHERE \n            ${whereConditionScript}${auditWhereClause};\n    END`;
        }

        script += `\n\n    ELSE IF @mode = 'A'\n    BEGIN\n        SELECT\n${selectFieldsFormatted}\n        FROM [${tblName}]\n    END\n\n    ELSE\n    BEGIN\n        RAISERROR ('Please select a valid mode', 16, 1)\n        RETURN;\n    END\nEND\nGO\n`;

        return script;
    };

    // 🔹 Merge Detail fields into Main SP parameters when toggle is OFF (false)
    let spRows = [];

    validRows.forEach(col => {
        if (col.dataType?.toUpperCase() === "GRID") {
            const rawFieldName = col.fieldName;
            const isSeparateTable = detailsTableTypes[rawFieldName] === true;

            if (!isSeparateTable) {
                // Combine child grid rows directly into main SP parameters
                const detailRows = detailsDataMap?.[rawFieldName] || detailsDataMap?.[cleanObjectName(rawFieldName)] || [];
                spRows.push(...getValidRows(detailRows));
            }
        } else {
            spRows.push(col);
        }
    });

    if (enableAudit) {
        spRows.push(
            { fieldName: 'company_code', dataType: 'VARCHAR', constraints: 'NN' },
            { fieldName: 'location_code', dataType: 'VARCHAR', constraints: 'NN' },
            { fieldName: 'created_by', dataType: 'VARCHAR', constraints: 'NN' },
            { fieldName: 'created_date', dataType: 'DATETIME' },
            { fieldName: 'modified_by', dataType: 'VARCHAR' },
            { fieldName: 'modified_date', dataType: 'DATETIME' }
        );
    }

    const outputFiles = {};

    // 1. Main Table Stored Procedure Script
    outputFiles[procName] = `/* =====================================================\n  MAIN TABLE STORED PROCEDURE\n===================================================== */\n\n` + buildStoredProc(spRows, tableName, procName);

    // 2. Details Table Stored Procedure Scripts (Only if toggle is ON / true)
    const gridFields = validRows.filter(r => r.dataType?.toUpperCase() === "GRID");

    gridFields.forEach(gridCol => {
        const rawFieldName = gridCol.fieldName;
        const isSeparateTable = detailsTableTypes[rawFieldName] === true;

        // Skip generating separate SP if user disabled "Treat as Separate Table"
        if (!isSeparateTable) return;

        const cleanGridName = cleanObjectName(rawFieldName);
        const currentDetailRows = detailsDataMap?.[rawFieldName] || detailsDataMap?.[cleanGridName] || [];

        if (currentDetailRows.length === 0) return;

        const detailsTableName = `tbl_${cleanGridName}`;
        const detailsProcName = `sp_${cleanGridName}`;

        let detailProcRows = getValidRows(currentDetailRows);

        if (enableAudit) {
            detailProcRows.push(
                { fieldName: 'company_code', dataType: 'VARCHAR', constraints: 'NN' },
                { fieldName: 'location_code', dataType: 'VARCHAR', constraints: 'NN' },
                { fieldName: 'created_by', dataType: 'VARCHAR', constraints: 'NN' },
                { fieldName: 'created_date', dataType: 'DATETIME' },
                { fieldName: 'modified_by', dataType: 'VARCHAR' },
                { fieldName: 'modified_date', dataType: 'DATETIME' }
            );
        }

        outputFiles[detailsProcName] = `/* =====================================================\n  DETAILS TABLE STORED PROCEDURE\n  TABLE : ${detailsTableName}\n===================================================== */\n\n` + buildStoredProc(detailProcRows, detailsTableName, detailsProcName);
    });

    return outputFiles;
};